name: deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: spotify-prod
    steps:
      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          sudo mv cloudflared /usr/local/bin/
          sudo chmod +x /usr/local/bin/cloudflared

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          echo "" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >> ~/.ssh/config <<EOF
          Host ssh.flamingo-lindo.com.br
            ProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h
            StrictHostKeyChecking no
            IdentityFile ~/.ssh/id_rsa
          EOF

      - name: Deploy to Raspberry Pi
        run: |
          sshpass -p "${{ secrets.SSH_KEY_PASSPHRASE }}" ssh ${{ secrets.SSH_USERNAME }}@ssh.flamingo-lindo.com.br "
            cd /home/flamingopi/Documents/..Dev &&
            git pull origin main &&
            docker compose build &&
            docker compose up -d --remove-orphans
          "