name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: spotify-prod
    steps:
      - name: Deploy to raspberrypi
        uses: appleboy/ssh-action@master
        with:
          host:      ${{ secrets.SSH_HOST_PROD }}
          username:  ${{ secrets.SSH_USERNAME }}t
          key:       ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: |
            cd /home/flamingopi/Documents/..Dev

            git pull origin main

            docker compose build
            docker compose up -d --remove-orphans