# name: deploy
# on:
#   push:
#     branches: [main]
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     environment: spotify-prod
#     steps:
#       - name: Install cloudflared
#         run: |
#           curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
#           sudo mv cloudflared /usr/local/bin/
#           sudo chmod +x /usr/local/bin/cloudflared

#       - name: Setup SSH
#         run: |
#           mkdir -p ~/.ssh
#           echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
#           echo "" >> ~/.ssh/id_ed25519
#           chmod 600 ~/.ssh/id_ed25519
#           cat >> ~/.ssh/config <<EOF
#           Host ssh.flamingo-lindo.com.br
#             ProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h
#             StrictHostKeyChecking no
#             IdentityFile ~/.ssh/id_ed25519
#           EOF

#       - name: Deploy to Raspberry Pi
#         run: |
#           ssh ${{ secrets.SSH_USERNAME }}@ssh.flamingo-lindo.com.br "
#             cd '/home/flamingopi/Documents/..Dev/Spotify-Request-Along' &&
#             git pull origin main &&
#             docker compose build &&
#             docker compose up -d --remove-orphans
#           "